In [1]:
import pandas as pd

In [6]:
customers = pd.DataFrame([
    ["C001", "Arun", "Kochi", "Kerala"],
    ["C002", "Rahul", "Bangalore", "Karnataka"],
    ["C003", "Priya", "Chennai", "Tamil Nadu"],
    ["C004", "Anjali", "Hyderabad", "Telangana"],
    ["C005", "John", "Mumbai", "Maharashtra"]
],
columns=[
    "customer_id",
    "customer_name",
    "city",
    "state"
])

customers

  customer_id customer_name       city        state
0        C001          Arun      Kochi       Kerala
1        C002         Rahul  Bangalore    Karnataka
2        C003         Priya    Chennai   Tamil Nadu
3        C004        Anjali  Hyderabad    Telangana
4        C005          John     Mumbai  Maharashtra

In [2]:
products = pd.DataFrame([
    ["P001", "Mobile", "Electronics"],
    ["P002", "Shoes", "Fashion"],
    ["P003", "Laptop", "Electronics"],
    ["P004", "Watch", "Accessories"],
    ["P005", "Headphones", "Electronics"]
],
columns=[
    "product_id",
    "product_name",
    "category"
])

products

  product_id product_name     category
0       P001       Mobile  Electronics
1       P002        Shoes      Fashion
2       P003       Laptop  Electronics
3       P004        Watch  Accessories
4       P005   Headphones  Electronics

In [3]:
orders = pd.DataFrame([
    ["O001", "C001", "P001", "2026-01-01", 2, 500, "South"],
    ["O002", "C002", "P002", "2026-01-02", 1, 1200, "North"],
    ["O003", "C003", "P003", "2026-01-03", 1, 55000, "South"],
    ["O004", "C004", "P004", "2026-01-03", 3, 2500, "East"],
    ["O005", "C005", "P005", "2026-01-04", 2, 1800, "West"]
],
columns=[
    "order_id",
    "customer_id",
    "product_id",
    "order_date",
    "quantity",
    "unit_price",
    "region"
])

orders

  order_id customer_id product_id  order_date  quantity  unit_price region
0     O001        C001       P001  2026-01-01         2         500  South
1     O002        C002       P002  2026-01-02         1        1200  North
2     O003        C003       P003  2026-01-03         1       55000  South
3     O004        C004       P004  2026-01-03         3        2500   East
4     O005        C005       P005  2026-01-04         2        1800   West

In [8]:
from google.colab import files

files.download("customers.csv")
files.download("products.csv")
files.download("orders.csv")
files.download("payments.csv")

In [4]:
payments = pd.DataFrame([
    ["O001", "UPI", "Success"],
    ["O002", "Credit Card", "Success"],
    ["O003", "UPI", "Success"],
    ["O004", "Debit Card", "Success"],
    ["O005", "UPI", "Pending"]
],
columns=[
    "order_id",
    "payment_mode",
    "payment_status"
])

payments

  order_id payment_mode payment_status
0     O001          UPI        Success
1     O002  Credit Card        Success
2     O003          UPI        Success
3     O004   Debit Card        Success
4     O005          UPI        Pending

In [7]:
customers.to_csv("customers.csv", index=False)
products.to_csv("products.csv", index=False)
orders.to_csv("orders.csv", index=False)
payments.to_csv("payments.csv", index=False)